import './globals.css'
import {Inter} from 'next/font/google'
import {SideBar} from "@/app/layout/SideBar";
import {TopBar} from "@/app/layout/TopBar";

const inter = Inter({subsets: ['latin']})

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
   children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <div className={'grid grid-cols-12'}>
            <TopBar/>
            <SideBar/>
            <div className={'col-span-10'}>
                {children}
            </div>
        </div>
        </body>
        </html>
    )
}
