import './globals.css'
import { Inter } from 'next/font/google'
import {NavBar} from "@/app/layout/NavBar";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className={'grid grid-cols-8'}>
            <NavBar />
            <div className={'col-span-7'}>
                {children}
            </div>
        </div>
      </body>
    </html>
  )
}
