import './globals.css'
import {Inter} from 'next/font/google'
import {TopBar} from "@/app/_components/layout/TopBar";

const inter = Inter({subsets: ['latin']})

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
   children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body className={inter.className}>
            <TopBar/>
            <div>
                {children}
            </div>
        </body>
        </html>
    )
}
